# Generated by Django 5.0.7 on 2024-07-20 22:14

import core.custom_functions.unique_file_path
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_alter_car_baseclass_alter_car_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('0', 'Motorsports'), ('1', 'Road Collection')], default='1', max_length=2)),
                ('sequence', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=254)),
                ('available_from_lvl', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.custom_functions.unique_file_path.get_unique_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('lenght', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('main_event', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80)),
                ('repeatable_series', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=254)),
                ('stages', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.custom_functions.unique_file_path.get_unique_file_path)),
                ('event_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventgroup')),
                ('featured_cars', models.ManyToManyField(related_name='featured_in_events', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='EventSubGroupRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(choices=[('0', '25%'), ('1', '50%'), ('2', '75%'), ('3', '100%'), ('4', 'Stage 1'), ('5', 'Stage 2'), ('6', 'Stage 3'), ('7', 'Stage 4'), ('8', 'Stage 5'), ('9', 'Stage 6'), ('10', 'Stage 7'), ('11', 'Stage 8'), ('12', 'Stage 9'), ('13', 'Stage 10')], default='0', max_length=2)),
                ('reward_amount_RS', models.IntegerField(default=0)),
                ('reward_amount_MS', models.IntegerField(default=0)),
                ('reward_amount_Gold', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.custom_functions.unique_file_path.get_unique_file_path)),
                ('event_subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventsubgroup')),
            ],
        ),
        migrations.CreateModel(
            name='TrackConfiguaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=254)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.track')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('0', 'Motorsports'), ('1', 'Road Collection')], default='1', max_length=2)),
                ('name', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=254)),
                ('special_event', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('page', models.IntegerField()),
                ('page_sequence', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('laps', models.IntegerField(default=0)),
                ('min_pr_requirements', models.DecimalField(decimal_places=1, max_digits=4)),
                ('time_required', models.DurationField()),
                ('reward', models.IntegerField()),
                ('reward_currency', models.CharField(choices=[('0', 'MS'), ('1', 'RS'), ('2', 'Gold'), ('3', 'Bonus')], default='1', max_length=2)),
                ('clean_race_bonus', models.IntegerField()),
                ('clean_race_bonus_currency', models.CharField(choices=[('0', 'MS'), ('1', 'RS'), ('2', 'Gold'), ('3', 'Bonus')], default='1', max_length=2)),
                ('reward_image', models.ImageField(blank=True, null=True, upload_to=core.custom_functions.unique_file_path.get_unique_file_path)),
                ('reward_fame', models.IntegerField()),
                ('fame_image', models.ImageField(blank=True, null=True, upload_to=core.custom_functions.unique_file_path.get_unique_file_path)),
                ('reward_in_one_minute_spent', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('fame_in_one_minute_spent', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.custom_functions.unique_file_path.get_unique_file_path)),
                ('event_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventgroup')),
                ('event_sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventsubgroup')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventtype')),
                ('track_and_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.trackconfiguaration')),
            ],
        ),
    ]
