# Generated by Django 5.0.7 on 2024-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_unique_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clean_race_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_pr_requirements',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_required',
            field=models.DurationField(default=0),
        ),
    ]
