# Generated by Django 5.0.7 on 2024-07-13 16:38

import core.custom_functions.unique_file_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Upgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_type', models.CharField(choices=[('0', 'Engine'), ('1', 'Drivetrain'), ('2', 'Body'), ('3', 'Suspension'), ('4', 'Exhaust'), ('5', 'Brakes'), ('6', 'Tires & Wheels')], default='0', max_length=1)),
                ('upgrade_heading', models.CharField(max_length=120)),
                ('upgrade_description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Upgrades',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=120)),
                ('section', models.CharField(choices=[('0', 'Motorsports'), ('1', 'Road Collection')], default='1')),
                ('default_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('currency', models.CharField(choices=[('0', 'MS'), ('1', 'RS'), ('2', 'Gold'), ('3', 'Bonus')], default='1')),
                ('delivery_time', models.DurationField()),
                ('baseclass', models.CharField(choices=[('0', 'P'), ('1', 'S'), ('2', 'R')], default='0')),
                ('eng_drive', models.CharField(choices=[('0', 'FF'), ('1', 'FR'), ('2', 'RR'), ('3', 'MR'), ('4', 'F4'), ('5', 'R4'), ('6', 'M4')], default='0')),
                ('init_top_speed', models.DecimalField(decimal_places=1, max_digits=4)),
                ('max_top_speed', models.DecimalField(decimal_places=1, max_digits=4)),
                ('init_acceleration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_acceleration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('init_braking_distance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('max_braking_distance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('official_braking_distance', models.BooleanField(default=True)),
                ('init_cornering', models.DecimalField(decimal_places=2, max_digits=3)),
                ('max_cornering', models.DecimalField(decimal_places=2, max_digits=3)),
                ('init_pr_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('max_pr_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('repair_time', models.DurationField()),
                ('repair_price', models.IntegerField()),
                ('repair_currency', models.CharField(choices=[('0', 'MS'), ('1', 'RS'), ('2', 'Gold'), ('3', 'Bonus')], default='1')),
                ('upgrades_total_R', models.IntegerField(default=0)),
                ('upgrades_total_M', models.IntegerField(default=0)),
                ('upgrades_total_G', models.IntegerField(default=0)),
                ('upgrades_total_G_optional', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.custom_functions.unique_file_path.get_unique_file_path)),
                ('full_info', models.BooleanField(default=False)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.custom_functions.unique_file_path.get_unique_file_path)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_sequence', models.IntegerField()),
                ('improvement_top_speed', models.DecimalField(decimal_places=1, max_digits=3)),
                ('improvement_acceleration', models.DecimalField(decimal_places=3, max_digits=4)),
                ('improvement_braking_distance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('improvement_cornering', models.DecimalField(decimal_places=3, max_digits=4)),
                ('improvement_pr', models.DecimalField(decimal_places=1, max_digits=3)),
                ('upgrade_option1_price', models.IntegerField()),
                ('upgrade_option1_currency', models.CharField(choices=[('0', 'MS'), ('1', 'RS'), ('2', 'Gold'), ('3', 'Bonus')], default='1')),
                ('upgrade_option2_price', models.IntegerField()),
                ('upgrade_option2_currency', models.CharField(choices=[('0', 'MS'), ('1', 'RS'), ('2', 'Gold'), ('3', 'Bonus')], default='2')),
                ('upgrade_time', models.DurationField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.custom_functions.unique_file_path.get_unique_file_path)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade', to='cars.car')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.upgrades')),
            ],
            options={
                'verbose_name_plural': 'Car Upgrades',
            },
        ),
    ]
